import * as fs from 'node:fs';
import * as path from 'node:path';

const I18N_DIR = path.resolve(__dirname, '../public/i18n');
const OUTPUT_FILE = path.resolve(__dirname, '../src/shared/types/i18n.generated.ts');

interface JsonValue {
  [key: string]: string | JsonValue;
}

function flattenKeys(object: JsonValue, prefix = ''): string[] {
  const keys: string[] = [];

  for (const [key, value] of Object.entries(object)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;

    if (typeof value === 'object') {
      keys.push(...flattenKeys(value, fullKey));
    } else {
      keys.push(fullKey);
    }
  }

  return keys;
}

function readJsonFile(filePath: string): JsonValue {
  const content = fs.readFileSync(filePath, 'utf-8');

  return JSON.parse(content) as JsonValue;
}

function discoverScopes(i18nDir: string): { scope: string; filePath: string }[] {
  const scopes: { scope: string; filePath: string }[] = [];

  // Global scope
  const globalFile = path.join(i18nDir, 'en.json');

  if (fs.existsSync(globalFile)) {
    scopes.push({ scope: '', filePath: globalFile });
  }

  // Scoped translations (subdirectories)
  const entries = fs.readdirSync(i18nDir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory()) {
      const scopeFile = path.join(i18nDir, entry.name, 'en.json');

      if (fs.existsSync(scopeFile)) {
        scopes.push({ scope: entry.name, filePath: scopeFile });
      }
    }
  }

  return scopes;
}

function generateTypes(): void {
  const scopes = discoverScopes(I18N_DIR);
  const allKeys: string[] = [];

  for (const { scope, filePath } of scopes) {
    const json = readJsonFile(filePath);
    const keys = flattenKeys(json);
    const prefixedKeys = scope ? keys.map((key) => `${scope}.${key}`) : keys;

    allKeys.push(...prefixedKeys);
  }

  allKeys.sort();

  const unionType = allKeys.map((key) => `  | '${key}'`).join('\n');

  const output = `// This file is auto-generated by scripts/generate-i18n-types.ts
// Do not edit manually. Run: npm run i18n:generate-types

export type TranslationKey =
${unionType};
`;

  const outputDirectory = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDirectory)) {
    fs.mkdirSync(outputDirectory, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

  console.log(`Generated ${String(allKeys.length)} translation keys → ${OUTPUT_FILE}`);
}

generateTypes();
