ALTER TABLE quiz_categories ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE NOT NULL DEFAULT '';
ALTER TABLE quiz_topics    ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE NOT NULL DEFAULT '';
ALTER TABLE quiz_questions ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE NOT NULL DEFAULT '';
ALTER TABLE quiz_answers   ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE NOT NULL DEFAULT '';
