import { ComponentFixture, TestBed } from '@angular/core/testing';
import { vi, type Mock } from 'vitest';
import { Router, ActivatedRoute, UrlTree, Event } from '@angular/router';
import { Observable, of, EMPTY } from 'rxjs';
import { SignInComponent } from './sign-in.component';
import { AuthService } from '@/core/services/auth.service';
import { UserStore } from '@/core/store/user.store';

// Note: These tests were generated by AI.
describe('SignInComponent', () => {
  let component: SignInComponent;
  let fixture: ComponentFixture<SignInComponent>;
  let mockAuthService: { login: Mock; getMe: Mock };
  let mockRouter: {
    navigate: Mock;
    createUrlTree: Mock;
    serializeUrl: Mock;
    events: Observable<Event>;
  };

  beforeEach(async () => {
    const fakeUser = { id: '1', email: 'test@example.com' };
    mockAuthService = {
      login: vi.fn().mockReturnValue(of({ accessToken: 'fake-token' })),
      getMe: vi.fn().mockReturnValue(of(fakeUser)),
    };

    // We will spy on the router to check if navigate was called
    mockRouter = {
      navigate: vi.fn().mockResolvedValue(true),
      createUrlTree: vi.fn().mockReturnValue({} as UrlTree),
      serializeUrl: vi.fn().mockReturnValue(''),
      events: EMPTY,
    };

    await TestBed.configureTestingModule({
      imports: [SignInComponent],
      providers: [
        { provide: AuthService, useValue: mockAuthService },
        { provide: Router, useValue: mockRouter },
        { provide: ActivatedRoute, useValue: {} },
        { provide: UserStore, useValue: { setUser: vi.fn() } },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(SignInComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create the component', () => {
    expect(component).toBeTruthy();
  });

  it('should initialize with an invalid form', () => {
    expect(component.signInForm.invalid).toBe(true);
  });

  it('should return error texts for invalid paths', () => {
    const emailControl = component.signInForm.get('email')!;
    emailControl.markAsTouched();
    expect(component.getErrorText('email')).toBe('This field is required');

    emailControl.setValue('not-an-email');
    expect(component.getErrorText('email')).toBe('Invalid email address');
  });

  it("shouldn't submit an invalid form", () => {
    mockAuthService.login.mockReturnValue(of({ accessToken: 'fake-token' }));

    component.onSubmit();
    expect(mockAuthService.login).not.toHaveBeenCalled();
  });

  it('should call login on successful form submit and navigate', () => {
    const fakeUser = { id: '1', email: 'test@example.com' };
    mockAuthService.login.mockReturnValue(of({ accessToken: 'test-token' }));
    mockAuthService.getMe.mockReturnValue(of(fakeUser));
    mockRouter.navigate.mockResolvedValue(true);

    component.signInForm.setValue({ email: 'test@example.com', password: 'password123' });
    component.onSubmit();

    expect(mockAuthService.login).toHaveBeenCalledWith({
      email: 'test@example.com',
      password: 'password123',
    });
    expect(mockRouter.navigate).toHaveBeenCalledWith(['/']);
  });
});
