import { ComponentFixture, TestBed } from '@angular/core/testing';
import { vi, type Mock } from 'vitest';
import { Router, ActivatedRoute, UrlTree, Event } from '@angular/router';
import { Observable, of, EMPTY } from 'rxjs';
import { SignUpComponent } from './sign-up.component';
import { AuthService } from '@/core/services/auth.service';
import { ROUTE_PATHS } from '@/core/constants';

// Note: These tests were generated by AI.
describe('SignUpComponent', () => {
  let component: SignUpComponent;
  let fixture: ComponentFixture<SignUpComponent>;
  let mockAuthService: { register: Mock };
  let mockRouter: {
    navigate: Mock;
    navigateByUrl: Mock;
    createUrlTree: Mock;
    serializeUrl: Mock;
    events: Observable<Event>;
  };

  beforeEach(async () => {
    mockAuthService = {
      register: vi.fn().mockReturnValue(
        of({
          id: 1,
          email: 'test@example.com',
          displayName: 'tester',
          createdAt: new Date(),
          updatedAt: new Date(),
        }),
      ),
    };

    mockRouter = {
      navigate: vi.fn().mockResolvedValue(true),
      navigateByUrl: vi.fn().mockResolvedValue(true),
      createUrlTree: vi.fn().mockReturnValue({} as UrlTree),
      serializeUrl: vi.fn().mockReturnValue(''),
      events: EMPTY,
    };

    await TestBed.configureTestingModule({
      imports: [SignUpComponent],
      providers: [
        { provide: AuthService, useValue: mockAuthService },
        { provide: Router, useValue: mockRouter },
        { provide: ActivatedRoute, useValue: {} },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(SignUpComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create the component', () => {
    expect(component).toBeTruthy();
  });

  it('should initialize with an invalid form', () => {
    expect(component.signUpForm.invalid).toBe(true);
  });

  it('should return error texts for invalid paths', () => {
    const passControl = component.signUpForm.get('password')!;

    passControl.markAsTouched();
    expect(component.getErrorText('password')).toBe('This field is required');

    passControl.setValue('short');
    expect(component.getErrorText('password')).toBe('Minimum length is 8 characters');
  });

  it('should not submit if form is invalid', () => {
    mockAuthService.register.mockReturnValue(
      of({
        id: 0,
        email: '',
        displayName: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
    );

    component.onSubmit();
    expect(mockAuthService.register).not.toHaveBeenCalled();
  });

  it('should call register on successful form submit and navigate to sign-in', () => {
    mockAuthService.register.mockReturnValue(
      of({
        id: 1,
        email: 'test@example.com',
        displayName: 'tester',
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
    );
    mockRouter.navigateByUrl.mockResolvedValue(true);

    // Valid values per our validators minimum lengths
    component.signUpForm.setValue({
      username: 'Jhon',
      email: 'jhon@example.com',
      password: 'mypassword123',
    });

    component.onSubmit();

    expect(mockAuthService.register).toHaveBeenCalledWith({
      displayName: 'Jhon',
      email: 'jhon@example.com',
      password: 'mypassword123',
    });
    expect(mockRouter.navigateByUrl).toHaveBeenCalledWith(ROUTE_PATHS.signIn);
  });
});
