import { ComponentFixture, TestBed } from '@angular/core/testing';
import { vi, type Mock } from 'vitest';
import { Router, ActivatedRoute, UrlTree, Event } from '@angular/router';
import { Observable, of, EMPTY } from 'rxjs';
import { SignUpComponent } from './sign-up.component';
import { AuthService } from '@/core/services/auth.service';
import { ROUTE_PATHS } from '@/core/constants';
import { AuthStore } from '@/core/store/auth.store';
import { ModalService, type ModalConfig } from '@/core/services/modal.service';
import { provideAppTranslocoTesting } from '@/testing/provide-transloco-testing';

// Note: These tests were generated by AI.
describe('SignUpComponent', () => {
  let component: SignUpComponent;
  let fixture: ComponentFixture<SignUpComponent>;
  let mockAuthService: { register: Mock };
  let mockAuthStore: { setUser: Mock };
  let mockModalService: { open: Mock };
  let mockRouter: {
    navigate: Mock;
    createUrlTree: Mock;
    serializeUrl: Mock;
    events: Observable<Event>;
  };

  beforeEach(async () => {
    mockAuthService = {
      register: vi.fn().mockReturnValue(
        of({
          id: 1,
          email: 'test@example.com',
          displayName: 'tester',
          createdAt: new Date(),
          updatedAt: new Date(),
        }),
      ),
    };

    mockRouter = {
      navigate: vi.fn().mockResolvedValue(true),
      createUrlTree: vi.fn().mockReturnValue({} as UrlTree),
      serializeUrl: vi.fn().mockReturnValue(''),
      events: EMPTY,
    };

    mockAuthStore = {
      setUser: vi.fn(),
    };

    mockModalService = {
      open: vi.fn().mockImplementation((options: ModalConfig) => {
        options.onClose?.();
      }),
    };

    await TestBed.configureTestingModule({
      imports: [SignUpComponent],
      providers: [
        provideAppTranslocoTesting(),
        { provide: AuthService, useValue: mockAuthService },
        { provide: Router, useValue: mockRouter },
        { provide: ActivatedRoute, useValue: {} },
        { provide: AuthStore, useValue: mockAuthStore },
        { provide: ModalService, useValue: mockModalService },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(SignUpComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create the component', () => {
    expect(component).toBeTruthy();
  });

  it('should initialize with an invalid form', () => {
    expect(component.signUpForm.invalid).toBe(true);
  });

  it('should return error texts for invalid paths', () => {
    const passControl = component.signUpForm.get('password')!;

    passControl.markAsTouched();
    expect(component.getValidationErrorKey('password')).toBe('auth.validation.required');

    passControl.setValue('short');
    expect(component.getValidationErrorKey('password')).toBe('auth.validation.minLength');
  });

  it('should not submit if form is invalid', () => {
    mockAuthService.register.mockReturnValue(
      of({
        id: 0,
        email: '',
        displayName: '',
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
    );

    component.onSubmit();
    expect(mockAuthService.register).not.toHaveBeenCalled();
  });

  it('should call register on successful form submit and navigate to sign-in', () => {
    mockAuthService.register.mockReturnValue(
      of({
        id: 1,
        email: 'test@example.com',
        displayName: 'tester',
        createdAt: new Date(),
        updatedAt: new Date(),
      }),
    );
    mockRouter.navigate.mockResolvedValue(true);

    // Valid values per our validators minimum lengths
    component.signUpForm.setValue({
      username: 'Jhon',
      email: 'jhon@example.com',
      password: 'MyPassword123!',
    });

    component.onSubmit();

    expect(mockAuthService.register).toHaveBeenCalledWith({
      displayName: 'Jhon',
      email: 'jhon@example.com',
      password: 'MyPassword123!',
    });
    expect(mockRouter.navigate).toHaveBeenCalledWith([ROUTE_PATHS.signIn]);
  });

  it('should not set user in AuthStore after successful registration', () => {
    component.signUpForm.setValue({
      username: 'Jhon',
      email: 'jhon@example.com',
      password: 'MyPassword123!',
    });

    component.onSubmit();

    expect(mockAuthStore.setUser).not.toHaveBeenCalled();
  });
});
